baseURL = "/"
languageCode = "en-us"
title = "pastly@home"
copyright = "© Matt Traudt"
theme = "risotto"
publishdir = "./publishdir"
paginate = 3
sectionPagesMenu = "main" # risotto
pluralizelisttitles = false

[params]
mainSections = ["posts", "camaro", "wsss"]

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[params.theme]
palette = "dracula"

[params.about]
title = "Matt Traudt (pastly)"
description = "Tech, Pets, and Vettes"
#description = "Tech, Pets, and Vettes. Not in that order."
#logo = "images/rice.svg"
images = [ "img/logos/rust.png", "img/logos/riley.png", "img/logos/c7zr1.png" ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # unsafe: render raw HTML. Okay as I'm the only one writing content.
      unsafe = true
    [markup.goldmark.extensions]
      # don't change quotes into fancy quotes, dashes into en/em-dashes, etc.
      typographer = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 1
